Repository Cecilia-Suarez/Ecos, pull requests merged in 2025-05, with the labels that each got.

#1 Music uploader and create event card components
  frontend/src/event/EventPage.tsx
  frontend/src/profile/ProfilePage.tsx
  frontend/src/profile/components/CreateEventCard.tsx
  frontend/src/profile/components/MusicUploader.tsx
  frontend/src/profile/components/ui/CalendarPlus.tsx
  frontend/src/routes/index.tsx
  frontend/src/shared/hooks/use-api-mutation.ts
Labels: enhancement

#37 Agregado de un nuevo Layout, EditProfilePage y theme de tailwind
  frontend/src/app/layout/BackButtonLayout.tsx
  frontend/src/app/layout/Header/BackButtonHeader.tsx
  frontend/src/app/ui/BackArrow.tsx
  frontend/src/app/ui/InstagramIcon.tsx
  frontend/src/app/ui/SpotifyIcon.tsx
  frontend/src/app/ui/TiktokIcon.tsx
  frontend/src/app/ui/YoutubeIcon.tsx
  frontend/src/assets/fonts/roboto.woff2
  frontend/src/auth/components/UserMenu.tsx
  frontend/src/index.css
  frontend/src/profile/EditProfilePage.tsx
  frontend/src/profile/ProfilePage.tsx
  frontend/src/profile/components/BannerUploader.tsx
  frontend/src/profile/components/ContactForm.tsx
  frontend/src/profile/components/FollowArtist.tsx
  frontend/src/profile/components/SpotifyTrack.tsx
  frontend/src/profile/components/YoutubeVideo.tsx
  frontend/src/routes/index.tsx
  frontend/src/shared/components/Cards/EventCard.tsx
Labels: tarea

#3 Refactor de DTO de canción y nuevos endpoints para banner y canciones de músico
  backend/src/main/java/com/footalentgroup/configuration/SecurityConfig.java
  backend/src/main/java/com/footalentgroup/controllers/MusicianProfileController.java
  backend/src/main/java/com/footalentgroup/controllers/SongController.java
  backend/src/main/java/com/footalentgroup/models/dtos/mapper/MusicProfileMapper.java
  backend/src/main/java/com/footalentgroup/models/dtos/mapper/SongMapper.java
  backend/src/main/java/com/footalentgroup/models/dtos/request/BannerUploadReqestDto.java
  backend/src/main/java/com/footalentgroup/models/dtos/request/MusicianProfileRequestDto.java
  backend/src/main/java/com/footalentgroup/models/dtos/request/SongPageRequestDto.java
  backend/src/main/java/com/footalentgroup/models/dtos/request/SongUploadRequestDto.java
  backend/src/main/java/com/footalentgroup/models/dtos/response/BannerResponseDto.java
  backend/src/main/java/com/footalentgroup/models/dtos/response/SongResponseDto.java
  backend/src/main/java/com/footalentgroup/models/entities/MusicianProfileEntity.java
  backend/src/main/java/com/footalentgroup/models/entities/SongEntity.java
  backend/src/main/java/com/footalentgroup/models/enums/SongSourceType.java
  backend/src/main/java/com/footalentgroup/repositories/SongRepository.java
  backend/src/main/java/com/footalentgroup/services/MusicianProfileService.java
  backend/src/main/java/com/footalentgroup/services/SongService.java
  backend/src/main/java/com/footalentgroup/services/impl/MusicianProfileServiceImpl.java
  backend/src/main/java/com/footalentgroup/services/impl/SongServiceImpl.java
Labels: tarea

#36 Associate tickets with event entity
  backend/src/main/java/com/footalentgroup/controllers/EventController.java
  backend/src/main/java/com/footalentgroup/models/dtos/mapper/EventMapper.java
  backend/src/main/java/com/footalentgroup/models/dtos/request/EventRequestDto.java
  backend/src/main/java/com/footalentgroup/models/dtos/request/TicketRequestDto.java
  backend/src/main/java/com/footalentgroup/models/dtos/response/EventResponseDto.java
  backend/src/main/java/com/footalentgroup/models/dtos/response/TicketResponseDto.java
  backend/src/main/java/com/footalentgroup/models/entities/EventEntity.java
  backend/src/main/java/com/footalentgroup/models/entities/TicketEntity.java
  backend/src/main/java/com/footalentgroup/models/enums/EventTicket.java
  backend/src/main/java/com/footalentgroup/services/impl/EventServiceImpl.java
Labels: tarea

#48 Improve Swagger documentation (Events, Auth, API)
  backend/src/main/java/com/footalentgroup/controllers/ApiController.java
  backend/src/main/java/com/footalentgroup/controllers/AuthController.java
  backend/src/main/java/com/footalentgroup/controllers/EventController.java
  backend/src/main/java/com/footalentgroup/models/dtos/request/EventRequestDto.java
  backend/src/main/java/com/footalentgroup/models/dtos/request/TicketRequestDto.java
Labels: documentation

#51 Remove debug prints
  backend/src/main/java/com/footalentgroup/configuration/JwtAuthenticationFilter.java
  backend/src/main/java/com/footalentgroup/controllers/FanProfileController.java
Labels: bug

#52 Update backend README
  backend/README.md
Labels: documentation

#58 Implement email service for contacting musicians
  backend/.env.example
  backend/pom.xml
  backend/src/main/java/com/footalentgroup/configuration/MailConfig.java
  backend/src/main/java/com/footalentgroup/controllers/MusicianProfileController.java
  backend/src/main/java/com/footalentgroup/exceptions/EmailSendingException.java
  backend/src/main/java/com/footalentgroup/exceptions/GlobalExceptionHandler.java
  backend/src/main/java/com/footalentgroup/models/dtos/request/ContactRequestDto.java
  backend/src/main/java/com/footalentgroup/services/EmailService.java
  backend/src/main/java/com/footalentgroup/services/impl/EmailServiceImpl.java
  backend/src/main/resources/application.properties
Labels: tarea

#63 Donation info
  backend/src/main/java/com/footalentgroup/controllers/MusicianProfileController.java
  backend/src/main/java/com/footalentgroup/models/dtos/mapper/MusicProfileMapper.java
  backend/src/main/java/com/footalentgroup/models/dtos/request/MusicianProfileRequestDto.java
  backend/src/main/java/com/footalentgroup/models/dtos/response/DonationResponseDto.java
  backend/src/main/java/com/footalentgroup/models/entities/MusicianProfileEntity.java
  backend/src/main/java/com/footalentgroup/repositories/MusicianProfileRepository.java
  backend/src/main/java/com/footalentgroup/services/MusicianProfileService.java
  backend/src/main/java/com/footalentgroup/services/impl/MusicianProfileServiceImpl.java
Labels: tarea

#64 Add donation fields to MusicianProfileResponseDto
  backend/src/main/java/com/footalentgroup/models/dtos/response/MusicianProfileResponseDto.java
Labels: tarea

#65 Perfil del músico, mejoras de UX y correcciones menores
  frontend/src/auth/components/ProtectedRoute.tsx
  frontend/src/auth/hooks/use-required-user.ts
  frontend/src/home/components/OptionsRegister.tsx
  frontend/src/index.css
  frontend/src/profile/EditProfilePage.tsx
  frontend/src/profile/ProfilePage.tsx
  frontend/src/profile/components/BannerUploader.tsx
  frontend/src/profile/components/CreateEventCard.tsx
  frontend/src/profile/components/MediaEmbedForm.tsx
  frontend/src/profile/components/MusicUploader.tsx
  frontend/src/profile/components/forms/FormFanProfile.tsx
  frontend/src/profile/components/forms/FormMusicianProfile.tsx
  frontend/src/profile/utils/media-utils.ts
  frontend/src/providers.tsx
  frontend/src/shared/hooks/use-api-mutation.ts
  frontend/src/shared/ui/ScrollToTop.tsx
Labels: tarea

#68 Replace pagination in Event
  backend/src/main/java/com/footalentgroup/models/dtos/mapper/EventMapper.java
  backend/src/main/java/com/footalentgroup/models/dtos/response/PagedResponseDto.java
  backend/src/main/java/com/footalentgroup/services/EventService.java
  backend/src/main/java/com/footalentgroup/services/impl/EventServiceImpl.java
Labels: tarea

#70 Implementacion de llamadas al Backend y arreglo de redireccionamiento
  frontend/eslint.config.js
  frontend/src/app/layout/Header/BackButtonHeader.tsx
  frontend/src/auth/components/UserMenu.tsx
  frontend/src/profile/hooks/use-media-embed.ts
  frontend/src/profile/musician/EditProfileMusicianPage.tsx
  frontend/src/profile/musician/components/MediaEmbedForm.tsx
  frontend/src/profile/musician/components/MusicUploader.tsx
  frontend/src/profile/utils/media-utils.ts
  frontend/src/shared/utils/axios-instance.ts
Labels: tarea

#71 Specify ResponseEntity types for event endpoints
  backend/src/main/java/com/footalentgroup/controllers/EventController.java
Labels: documentation

#72 Return ID in MusicianInfoResponseDto & photoUrl in DonationResponseDto
  backend/src/main/java/com/footalentgroup/models/dtos/mapper/SongMapper.java
  backend/src/main/java/com/footalentgroup/models/dtos/response/DonationResponseDto.java
  backend/src/main/java/com/footalentgroup/models/dtos/response/MusicianInfoResponseDto.java
  backend/src/main/java/com/footalentgroup/models/dtos/response/SongResponseDto.java
  backend/src/main/java/com/footalentgroup/repositories/MusicianProfileRepository.java
  backend/src/main/java/com/footalentgroup/services/impl/MusicianFollowsServiceImlp.java
  backend/src/main/java/com/footalentgroup/services/impl/SongServiceImpl.java
Labels: bug

#80 Add description to MusicianProfileEntity & Search endpoint
  backend/src/main/java/com/footalentgroup/configuration/SecurityConfig.java
  backend/src/main/java/com/footalentgroup/controllers/MusicianProfileController.java
  backend/src/main/java/com/footalentgroup/models/dtos/mapper/MusicProfileMapper.java
  backend/src/main/java/com/footalentgroup/models/dtos/request/MusicianProfileRequestDto.java
  backend/src/main/java/com/footalentgroup/models/dtos/request/MusicianSearchRequestDTO.java
  backend/src/main/java/com/footalentgroup/models/dtos/response/MusicianProfileResponseDto.java
  backend/src/main/java/com/footalentgroup/models/dtos/response/MusicianSimpleResponseDto.java
  backend/src/main/java/com/footalentgroup/models/entities/MusicianProfileEntity.java
  backend/src/main/java/com/footalentgroup/repositories/MusicianProfileRepository.java
  backend/src/main/java/com/footalentgroup/services/MusicianProfileService.java
  backend/src/main/java/com/footalentgroup/services/impl/MusicianProfileServiceImpl.java
Labels: tarea

#82 Creacion del README, AudioPlayer, DonateSection, DonateButton, HearteButton y acutalizacion de la MusicianProfilePage
  frontend/README.md
  frontend/src/app/layout/Header/BackButtonHeader.tsx
  frontend/src/app/ui/Button.tsx
  frontend/src/app/ui/InstagramIcon.tsx
  frontend/src/app/ui/SpotifyIcon.tsx
  frontend/src/app/ui/TiktokIcon.tsx
  frontend/src/app/ui/YoutubeIcon.tsx
  frontend/src/profile/components/ContactForm.tsx
  frontend/src/profile/components/DonateButton.tsx
  frontend/src/profile/components/HeartButton.tsx
  frontend/src/profile/components/ui/Donate.tsx
  frontend/src/profile/components/ui/Heart.tsx
  frontend/src/profile/musician/EditProfileMusicianPage.tsx
  frontend/src/profile/musician/ProfileMusicianPage.tsx
  frontend/src/profile/musician/components/AudioPlayer.tsx
  frontend/src/profile/musician/components/DonateSection.tsx
  frontend/src/profile/musician/components/FollowArtist.tsx
  frontend/src/routes/index.tsx
  frontend/src/shared/components/Cards/EventCard.tsx
Labels: tarea

#84 Add @PreAuthorize annotations for role-based access control
  backend/src/main/java/com/footalentgroup/configuration/SecurityConfig.java
  backend/src/main/java/com/footalentgroup/controllers/FanProfileController.java
  backend/src/main/java/com/footalentgroup/controllers/MusicianProfileController.java
  backend/src/main/java/com/footalentgroup/controllers/SavedSongController.java
  backend/src/main/java/com/footalentgroup/controllers/SongController.java
Labels: tarea

#85 Adjust JWT environment variables and add missing test configurations
  backend/src/main/java/com/footalentgroup/services/JwtService.java
  backend/src/test/resources/logback-test.xml
  backend/src/test/resources/test.properties
Labels: bug

#89 Add project documentation
  README.md
  assets/ecos.png
Labels: documentation

#90 Agregado de SEO, mejora de lógica en EditProfilePage, ProfilePage y responsive
  frontend/index.html
  frontend/public/favicon-dark.ico
  frontend/public/favicon.ico
  frontend/public/vite.svg
  frontend/src/auth/components/UserMenu.tsx
  frontend/src/auth/components/ui/UserProfileIcon.tsx
  frontend/src/profile/components/forms/shemas/ProfileSchema.ts
  frontend/src/profile/components/ui/ArrowDown.tsx
  frontend/src/profile/musician/EditProfileMusicianPage.tsx
  frontend/src/profile/musician/ProfileMusicianPage.tsx
  frontend/src/profile/musician/components/FollowArtist.tsx
  frontend/src/profile/musician/components/YoutubeVideo.tsx
  frontend/src/profile/musician/musician-types.ts
  frontend/src/providers.tsx
Labels: tarea

#93 Correct event query
  backend/src/main/java/com/footalentgroup/repositories/EventRepository.java
  backend/src/main/java/com/footalentgroup/services/impl/EventServiceImpl.java
Labels: bug

#95 Lógica de favoritos y donacion en el perfil del músico y mejoras en los estilos de las imagenes
  frontend/src/app/layout/Header/Header.tsx
  frontend/src/profile/fan/DonationModal.tsx
  frontend/src/profile/fan/components/CardSong.tsx
  frontend/src/profile/fan/ui/PauseIcon.tsx
  frontend/src/profile/musician/ProfileMusicianPage.tsx
  frontend/src/profile/musician/components/DonateSection.tsx
  frontend/src/profile/musician/musician-types.ts
Labels: bug, tarea

#97 Limpieza de codigo e implementacion de eventos y contacto al músico
  frontend/src/auth/components/LoginForm.tsx
  frontend/src/auth/components/RegistrationForm.tsx
  frontend/src/auth/components/UserMenu.tsx
  frontend/src/event/components/step/StepFour.tsx
  frontend/src/profile/components/forms/FormMusicianProfile.tsx
  frontend/src/profile/musician/EditProfileMusicianPage.tsx
  frontend/src/profile/musician/ProfileMusicianPage.tsx
  frontend/src/profile/musician/components/ContactForm.tsx
  frontend/src/profile/musician/components/DonateSection.tsx
  frontend/src/profile/musician/components/FollowArtist.tsx
  frontend/src/profile/musician/musician-types.ts
  frontend/src/shared/components/Cards/EventCard.tsx
Labels: tarea

#100 Fix: error al visitar el profile del músico como invitado
  frontend/src/profile/musician/ProfileMusicianPage.tsx
Labels: bug

#101 Mejora del Footer y agregado de templates para los videos y archivos de audio
  frontend/src/app/layout/Footer/Footer.tsx
  frontend/src/app/layout/Header/Bell.tsx
  frontend/src/app/layout/Header/Header.tsx
  frontend/src/app/ui/LinkedInIcon.tsx
  frontend/src/assets/EcosLogoFooter.webp
  frontend/src/assets/avatar.svg
  frontend/src/assets/iconoFacebook.svg
  frontend/src/assets/iconoInstagram.svg
  frontend/src/assets/iconoTiktok.svg
  frontend/src/assets/iconoYoutube.svg
  frontend/src/index.css
  frontend/src/profile/musician/ProfileMusicianPage.tsx
  frontend/src/profile/musician/components/MediaSkeleton.tsx
Labels: tarea

#106 Add musician info to EventSimpleResponseDto
  backend/src/main/java/com/footalentgroup/models/dtos/mapper/EventMapper.java
  backend/src/main/java/com/footalentgroup/models/dtos/response/EventSimpleResponseDto.java
Labels: bug

#116 Redirección basada en roles en LoginForm
  frontend/src/auth/components/LoginForm.tsx
Labels: tarea

#117 Convertir enlace de pago en un enlace interactivo
  frontend/src/profile/fan/components/DonationDataReadOnlySection.tsx
  frontend/src/profile/fan/components/LabeledFieldReadOnly.tsx
  frontend/src/profile/fan/components/LabeledLinkReadOnly.tsx
Labels: tarea

#118 Mejorar lógica de enlaces de músicos
  frontend/src/profile/musician/components/FollowArtist.tsx
Labels: bug

#120 Responsive del perfil del músico y Spinner
  frontend/src/app/ui/Spinner.tsx
  frontend/src/profile/components/DonateButton.tsx
  frontend/src/profile/components/HeartButton.tsx
  frontend/src/profile/musician/ProfileMusicianPage.tsx
  frontend/src/profile/musician/components/MediaSkeleton.tsx
  frontend/src/shared/components/Cards/EventCard.tsx
Labels: tarea

#123 Remove unused imports and commented code
  backend/src/main/java/com/footalentgroup/models/dtos/request/SongUploadRequestDto.java
  backend/src/main/java/com/footalentgroup/repositories/FanProfileRepository.java
  backend/src/main/java/com/footalentgroup/repositories/SavedSongRepository.java
  backend/src/main/java/com/footalentgroup/repositories/SongRepository.java
  backend/src/main/java/com/footalentgroup/services/AuthService.java
  backend/src/main/java/com/footalentgroup/services/SongService.java
  backend/src/main/java/com/footalentgroup/services/impl/FanProfileServiceImp.java
  backend/src/main/java/com/footalentgroup/services/impl/SongServiceImpl.java
  backend/src/test/java/com/footalentgroup/repositories/DatabaseSeederService.java
Labels: bug

#122 Mejoras en botones de guardar y donar
  frontend/src/index.css
  frontend/src/profile/components/HeartButton.tsx
  frontend/src/profile/fan/components/FavoriteSongList.tsx
  frontend/src/profile/musician/ProfileMusicianPage.tsx
  frontend/src/profile/types/favorite-songs.ts
  frontend/src/shared/hooks/use-api-query.ts
Labels: tarea

#125 Reemplazo de los componentes por imports directos de svg
  frontend/src/app/layout/Footer/Footer.tsx
  frontend/src/app/ui/InstagramIcon.tsx
  frontend/src/app/ui/LinkedInIcon.tsx
  frontend/src/app/ui/SpotifyIcon.tsx
  frontend/src/app/ui/YoutubeIcon.tsx
  frontend/src/assets/RRSS/instagram.svg
  frontend/src/assets/RRSS/linkedin.svg
  frontend/src/assets/RRSS/spotify.svg
  frontend/src/assets/RRSS/youtube.svg
  frontend/src/profile/musician/ProfileMusicianPage.tsx
  frontend/src/profile/musician/components/FollowArtist.tsx
Labels: tarea

#127 Ajuste de estilos en Button para alineación con el diseño
  frontend/src/app/ui/Button.tsx
  frontend/src/index.css
Labels: bug, tarea

#128 Agregado de carpeta para types dentro de app y arreglo de type en carpeta schemas
  frontend/src/app/components/EventById.tsx
  frontend/src/app/types/event-by-id-types.d.ts
  frontend/src/profile/components/forms/FormFanProfile.tsx
  frontend/src/profile/components/forms/FormMusicianProfile.tsx
  frontend/src/profile/components/forms/components/sections/ContactDetailsMusicianSection.tsx
  frontend/src/profile/components/forms/components/sections/DonationDataSection.tsx
  frontend/src/profile/components/forms/components/sections/PersonalDataFanSection.tsx
  frontend/src/profile/components/forms/components/sections/PersonalDataMusicianSection.tsx
  frontend/src/profile/components/forms/components/sections/SocialLinksSection.tsx
  frontend/src/profile/components/forms/schemas/ProfileSchema.ts
  frontend/src/profile/hooks/use-load-fan-form.ts
  frontend/src/profile/hooks/use-load-musician-form.ts
  frontend/src/profile/utils/handlers/handle-fan-profile-submit.ts
  frontend/src/profile/utils/handlers/handle-musician-profile-submit.ts
Labels: bug

#129 Renderizado de componentes en base al ID del usuario identificado con el ID de la URL
  frontend/src/app/layout/Footer/Footer.tsx
  frontend/src/profile/musician/ProfileMusicianPage.tsx
  frontend/src/profile/musician/components/DonateSection.tsx
Labels: bug

#131 Refactorizacion del Header y arreglo de algunos estilos
  frontend/src/app/layout/Header/Header.tsx
  frontend/src/assets/header/logo.svg
  frontend/src/auth/components/RoleSelector.tsx
  frontend/src/auth/components/UserMenu.tsx
  frontend/src/home/HomePage.tsx
  frontend/src/home/components/sections/DiscoverArtist.tsx
  frontend/src/home/components/sections/FAQList.tsx
  frontend/src/home/components/sections/FeaturedArtists.tsx
  frontend/src/home/components/sections/Hero.tsx
  frontend/src/home/components/sections/UpcomingEvents.tsx
  frontend/src/vite-env.d.ts
Labels: bug, tarea

#133 Actualizar avatar de usuario instantáneamente tras editar foto de perfil
  frontend/src/auth/components/UserMenu.tsx
  frontend/src/profile/components/forms/FormFanProfile.tsx
  frontend/src/profile/components/forms/FormMusicianProfile.tsx
  frontend/src/profile/hooks/use-profile-form.ts
Labels: bug

#134 Mejora del Header, Botón de agregar al calendario y arreglo de estilos
  frontend/src/app/components/EventById.tsx
  frontend/src/app/layout/Footer/Footer.tsx
  frontend/src/app/layout/Header/BackButtonHeader.tsx
  frontend/src/app/layout/Header/Header.tsx
  frontend/src/app/ui/Spinner.tsx
  frontend/src/app/utils/parse-date-time.ts
  frontend/src/auth/components/LoginForm.tsx
  frontend/src/auth/components/RegistrationForm.tsx
  frontend/src/event/components/ui/CalendarButton.tsx
  frontend/src/event/components/ui/Icons.tsx
  frontend/src/explorer/components/ExplorerPage.tsx
  frontend/src/home/components/FeaturedSongs.tsx
  frontend/src/profile/fan/ProfileFanPage.tsx
  frontend/src/profile/fan/components/FavoriteSongList.tsx
  frontend/src/routes/index.tsx
  frontend/src/shared/components/Cards/OptionsRegisterCards.tsx
Labels: bug, tarea

#137 Ajuste de estilos en Button
  frontend/src/app/ui/Button.tsx
  frontend/src/index.css
Labels: tarea

#141 Ajuste de estilos en Login & Registro
  frontend/src/auth/components/AuthModal.tsx
  frontend/src/auth/components/LoginForm.tsx
  frontend/src/auth/components/RegistrationForm.tsx
  frontend/src/auth/components/RoleSelector.tsx
  frontend/src/auth/components/WelcomeUserModal.tsx
Labels: bug, tarea

#142 Mejora de estilos en las rutas del músico y componente Logo
  frontend/src/app/components/Logo.tsx
  frontend/src/assets/fonts/nunito.woff2
  frontend/src/index.css
  frontend/src/profile/components/BannerUploader.tsx
  frontend/src/profile/components/ui/Icons.tsx
  frontend/src/profile/musician/EditProfileMusicianPage.tsx
  frontend/src/profile/musician/ProfileMusicianPage.tsx
  frontend/src/profile/musician/components/ContactForm.tsx
  frontend/src/profile/musician/components/CreateEventCard.tsx
  frontend/src/profile/musician/components/FollowArtist.tsx
  frontend/src/profile/musician/components/MediaEmbedForm.tsx
  frontend/src/profile/musician/components/MusicUploader.tsx
  frontend/src/shared/components/Cards/EventCard.tsx
Labels: bug, tarea

#143 Ajuste de estilos en sección de Registro y Ver eventos
  frontend/src/assets/iconoE.svg
  frontend/src/assets/iconoF.svg
  frontend/src/assets/iconoM.svg
  frontend/src/home/components/sections/OptionsRegister.tsx
  frontend/src/shared/components/Cards/OptionsRegisterCards.tsx
Labels: bug, tarea

#145 Actualizacion del perfil del músico
  frontend/src/app/components/Logo.tsx
  frontend/src/app/ui/Icons.tsx
  frontend/src/home/components/CardSong.tsx
  frontend/src/home/components/ui/Icons.tsx
  frontend/src/profile/components/BannerUploader.tsx
  frontend/src/profile/components/ui/Icons.tsx
  frontend/src/profile/fan/components/CardSong.tsx
  frontend/src/profile/hooks/use-media-embed.ts
  frontend/src/profile/musician/EditProfileMusicianPage.tsx
  frontend/src/profile/musician/components/AudioPlayer.tsx
  frontend/src/profile/musician/components/CreateEventCard.tsx
  frontend/src/profile/musician/components/MediaEmbedForm.tsx
  frontend/src/profile/musician/components/MusicUploader.tsx
Labels: bug, tarea

#144 Página 404
  frontend/src/app/ui/NotFound.tsx
  frontend/src/routes/index.tsx
Labels: tarea

#147 Actualizacion del componente Hero en Home
  frontend/src/app/components/EventById.tsx
  frontend/src/home/components/sections/Hero.tsx
Labels: bug, tarea

#148 Ajuste de estilos y estructura en tarjetas de Eventos
  frontend/src/shared/components/Cards/EventCard.tsx
Labels: bug, tarea

#149 Rutas protegidas por rol, renderizado del perfil del músico por rol y cambio de navegacion en el menu
  frontend/src/auth/components/LoginForm.tsx
  frontend/src/auth/components/ProtectedRoute.tsx
  frontend/src/auth/components/RegistrationForm.tsx
  frontend/src/auth/components/UserMenu.tsx
  frontend/src/auth/components/ui/Icons.tsx
  frontend/src/profile/components/DonateButton.tsx
  frontend/src/profile/components/HeartButton.tsx
  frontend/src/profile/musician/ProfileMusicianPage.tsx
  frontend/src/profile/musician/components/DonateSection.tsx
  frontend/src/routes/index.tsx
Labels: bug, tarea

#157 Arreglos en los modales y botones de la Home
  frontend/src/app/ui/Input.tsx
  frontend/src/home/components/sections/Hero.tsx
  frontend/src/home/components/sections/OptionsRegister.tsx
  frontend/src/index.css
  frontend/src/profile/components/ProfileUserModal.tsx
  frontend/src/profile/components/forms/FormFanProfile.tsx
  frontend/src/profile/components/forms/FormMusicianProfile.tsx
  frontend/src/profile/components/forms/components/sections/ProfilePhotoSection.tsx
  frontend/src/profile/components/forms/components/sections/SocialLinksSection.tsx
  frontend/src/profile/components/ui/Icons.tsx
  frontend/src/profile/musician/ProfileMusicianPage.tsx
  frontend/src/shared/components/Cards/OptionsRegisterCards.tsx
Labels: bug

#158 Eliminar prints de consola y mensajes de debug
  frontend/src/auth/components/ForgotPasswordForm.tsx
  frontend/src/auth/context/AuthProvider.tsx
  frontend/src/profile/fan/components/CardSong.tsx
  frontend/src/profile/fan/components/LabeledFieldReadOnly.tsx
Labels: bug

#164 Lógica de busqueda
  frontend/src/app/components/MusicSearch.tsx
  frontend/src/app/components/SearchCard.tsx
  frontend/src/app/types/musician-profile-search.d.ts
  frontend/src/app/types/search-normalize-data.d.ts
  frontend/src/profile/musician/musician-types.ts
  frontend/src/shared/hooks/use-debounce.ts
Labels: tarea

#166 Ajuste de textos
  frontend/src/app/components/CardArtist.tsx
  frontend/src/app/components/EventById.tsx
  frontend/src/app/components/MusicSearch.tsx
  frontend/src/app/layout/Header/Header.tsx
  frontend/src/event/components/step/StepFour.tsx
  frontend/src/event/components/step/StepOne.tsx
  frontend/src/event/components/step/StepTwo.tsx
  frontend/src/home/components/CardSong.tsx
  frontend/src/home/components/FeaturedSongs.tsx
  frontend/src/profile/components/forms/components/sections/ContactDetailsMusicianSection.tsx
Labels: bug
